- name: Deploy from GIT
  hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "repo url: {{ repo_url }} dest_folder: {{ dest_folder }}"

    - name: git checkout
      git:
        repo: "{{ repo_url }}"
        dest: /tmp
        delegate_to: localhost

    - name: copy module
      synchronize:
        src: /tmp
        dest: "{{ dest_folder }}"
