- name: Deploy from GIT
  hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "repo url: {{ repo_url }} dest_folder: {{ dest_folder }}"

    - name: remove old files from temp
      file:
        path: "{{ dest_folder }}"
        state: absent

    - name: Creates directory
      file:
        path: "{{ dest_folder }}"
        state: directory

    - name: git checkout
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_folder }}"
      register: gitResult

    - debug:
        msg: "GIT Results: {{gitResult}}"

