- name: Deploy from GIT
  hosts: all
  gather_facts: true
  tasks:
    - debug:
        msg: "repo url: {{ repo_url }} dest_folder: {{ dest_folder }}"

    - name: remove old files from temp
      file:
        path: /tmp/testGit
        state: absent

    - name: remove old files from temp
      file:
        path: "{{ dest_folder }}"
        state: absent

    - name: git checkout
      git:
        repo: "{{ repo_url }}"
        dest: /tmp/testGit

    - name: copy module
      synchronize:
        src: /tmp/testGit/*
        dest: "{{ dest_folder }}"
